tasks:
  - init: yarn
    command: yarn solve
    name: solve

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: false

vscode:
  extensions:
    - esbenp.prettier-vscode@5.8.0:ZYZPKhQWgwL819tHuvpssw==
